on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main 


name: Simple Workflow

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: JFrog config 
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}   
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: ${{secrets.JF_REGISTRY}}
          
      - name: Node install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}  

      - name: Run test
        run: npm run sonar-test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Run build
        run: npm run build

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: |
          jfrog npm run build
          jfrog rt upload "build/" default-npm-local/ 
          jfrog rt bp
